### ISSUE TITLE
Encode jpg to web, the file will be rotation.

### ISSUE THREAD

**Issue by rluisr** [Intervox/node-webp#16]
# This is original.
![image](https://user-images.githubusercontent.com/7776462/35811042-dd1c9c36-0ad0-11e8-94ed-3cf7228afdfd.png)

# Encoded to webp
![image](https://user-images.githubusercontent.com/7776462/35811259-5ee3ed28-0ad1-11e8-8738-3a996692ef7d.png)

So I encoded to web, the file is rotated.
how to solve this problem?

``` Javascript
const encoder = new CWebp(imgBuf);
  encoder.quality(80);
  encoder.toBuffer((err, buf) => {
    if (err) {
      console.log('encode error');
      reject(err);
    }
    resolve(buf);
  });
```

**Comment by lbeschastny** [comment]
I was unable to reproduce the problem with the image you've provided.
But the problem itself is well known.
So I'll assume that "original" image here is not the actual original image, but it's processed copy.

So, here is your actual problem.

Your original image contained [Exif] metadata with information about it's orientation.
So, the actual original image was also rotated, just like the encoded one.
But is also contained exif rotation metadata, telling how it should be displayed to the user.
Since most modern image viewers respect exif metadata, you never saw the real image.

I would also guess that you took this photo with your phone (most likely iPhone).
It's common practice for mobile devices (and especially apple mobile devices) to substitute actual photo rotation with corresponding exif metadata.
All image-related services in the web know about exif and strip it along with all other metadata during photo pre-processing, actually rotating your photo instead.

I could see two possible solutions for your problem.

First, you could use cwebp [metadata] flag (by using corresponding [.metadata] helper method) to preserve original exif metadata:

```js
encoder.metadata('exif');
```

But I would recommend you to strip exif metadata and manually rotate the photo instead.
Otherwise it may not be displayed correctly to all of your users.

Unfortunately, webp can't do it for you. So, you'll have to use a real image-processing tool to handle it.

I would suggest using [gm]. It support both [GraphicsMagick] and [ImageMagick] processing libraries and it already have a build-in function to handle exif rotation: [gm#autoOrient].

 [Exif]: https://en.wikipedia.org/wiki/Exif
 [metadata]: https://developers.google.com/speed/webp/docs/cwebp#additional_options
 [.metadata]: https://github.com/Intervox/node-webp/blob/246546853d6876f8723c562bca460c3cbbc48fa1/methods.json#L160-L162
 [gm]: http://npmjs.com/package/gm
 [GraphicsMagick]: http://www.graphicsmagick.org/
 [ImageMagick]: http://www.imagemagick.org/script/index.php
 [gm#autoOrient]: http://aheckmann.github.io/gm/docs.html#autoOrient

**Comment by rluisr** [comment]
Thanks @lbeschastny 
I switch to gm and solve this problem.

Thank you for teaching me kind.

**Comment by lbeschastny** [comment]
@rluisr does `gm` have build-in `.webp` support now?
The last time I checked you had to use a dedicated webp converter after processing your image with `gm`.

Looks like both GraphicsMagick and ImageMagick finally added full webp support.
Glad to hear it.

**Comment by rluisr** [comment]
@lbeschastny 
yes. `gm` supports `.webp`.
![image](https://user-images.githubusercontent.com/7776462/35903543-ff22039a-0c22-11e8-8486-47cc65cd4361.png)

Thanks :-)
